export const SRSColors = {
  light: {
    primary: '#6366F1',
    primaryLight: '#E0E7FF',
    success: '#22C55E',
    successLight: '#DCFCE7',
    warning: '#F59E0B',
    warningLight: '#FEF3C7',
    danger: '#EF4444',
    dangerLight: '#FEE2E2',
    card: '#FFFFFF',
    cardBorder: '#E5E7EB',
    accent: '#8B5CF6',
    accentLight: '#EDE9FE',
    surface: '#F9FAFB',
    surfaceVariant: '#F3F4F6',
  },
  dark: {
    primary: '#818CF8',
    primaryLight: '#1E1B4B',
    success: '#4ADE80',
    successLight: '#14532D',
    warning: '#FBBF24',
    warningLight: '#78350F',
    danger: '#F87171',
    dangerLight: '#7F1D1D',
    card: '#1C1C1E',
    cardBorder: '#2C2C2E',
    accent: '#A78BFA',
    accentLight: '#2E1065',
    surface: '#1C1C1E',
    surfaceVariant: '#2C2C2E',
  },
} as const;

export type SRSColor = keyof typeof SRSColors.light;
